"use client";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { services, validateBooking, type BookingInput, type Booking } from "./booking-options";

type Field = { key:string; label:string; placeholder:string; type?:"text"|"textarea" };
const formConfigs: Record<string,{ heading:string; partner:string; businessLabel:string; locationLabel:string; locationPlaceholder:string; fields:Field[] }> = {
  products:{ heading:"ข้อมูลพื้นที่ของคุณ",partner:"space",businessLabel:"ชื่อพื้นที่ / ธุรกิจ",locationLabel:"ทำเลของพื้นที่",locationPlaceholder:"ระบุเขต จังหวัด หรือชื่อสถานที่",fields:[{key:"spaceType",label:"ประเภทพื้นที่",placeholder:"เช่น คาเฟ่ ร้านค้า โรงแรม Wellness"},{key:"customerProfile",label:"กลุ่มลูกค้าหลัก",placeholder:"อธิบายกลุ่มลูกค้าที่ใช้พื้นที่เป็นประจำ",type:"textarea"},{key:"availableArea",label:"พื้นที่หรือจุดที่พร้อมใช้งาน",placeholder:"เช่น เคาน์เตอร์ ชั้นวางสินค้า ล็อบบี้ หรือพื้นที่กิจกรรม"},{key:"productCategories",label:"หมวดสินค้าที่สนใจ",placeholder:"เช่น สุขภาพ ความงาม อาหาร เครื่องดื่ม หรือยังไม่แน่ใจ"}]},
  space:{ heading:"ข้อมูลสินค้าและพื้นที่ที่สนใจ",partner:"brand",businessLabel:"ชื่อแบรนด์ / ธุรกิจ",locationLabel:"พื้นที่หรือทำเลที่สนใจ",locationPlaceholder:"ระบุเขต จังหวัด หรือประเภทพื้นที่ที่ต้องการ",fields:[{key:"productName",label:"ชื่อสินค้า",placeholder:"ชื่อสินค้าหรือกลุ่มผลิตภัณฑ์"},{key:"productCategory",label:"หมวดสินค้า",placeholder:"เช่น สุขภาพ ความงาม อาหาร เครื่องดื่ม"},{key:"priceRange",label:"ช่วงราคาขาย",placeholder:"เช่น 200–500 บาท"},{key:"targetCustomer",label:"กลุ่มลูกค้าเป้าหมาย",placeholder:"อธิบายกลุ่มลูกค้าที่ต้องการเข้าถึง",type:"textarea"},{key:"preferredArea",label:"ลักษณะพื้นที่ที่ต้องการ",placeholder:"เช่น คาเฟ่ โรงแรม ร้านค้า หรือพื้นที่ Wellness"}]},
  popup:{ heading:"ข้อมูล Pop-up ที่ต้องการจัด",partner:"brand",businessLabel:"ชื่อแบรนด์ / ผู้จัด",locationLabel:"พื้นที่หรือทำเลที่สนใจ",locationPlaceholder:"ระบุเขต จังหวัด หรือบรรยากาศพื้นที่ที่ต้องการ",fields:[{key:"popupFormat",label:"รูปแบบ Pop-up",placeholder:"เช่น ทดลองขาย เปิดตัวสินค้า หรือ Brand Activation"},{key:"campaignGoal",label:"เป้าหมายของ Pop-up",placeholder:"อธิบายสิ่งที่ต้องการให้เกิดขึ้นจากกิจกรรม",type:"textarea"},{key:"preferredArea",label:"ลักษณะพื้นที่ที่ต้องการ",placeholder:"ขนาด บรรยากาศ หรือข้อกำหนดสำคัญ"},{key:"duration",label:"ระยะเวลาที่ต้องการ",placeholder:"เช่น 1 วัน, 3 วัน หรือ 1 สัปดาห์"}]},
  workshop:{ heading:"ข้อมูลกิจกรรม / Workshop",partner:"organizer",businessLabel:"ชื่อองค์กร / ผู้จัด",locationLabel:"พื้นที่หรือทำเลที่สนใจ",locationPlaceholder:"ระบุเขต จังหวัด หรือรูปแบบสถานที่",fields:[{key:"activityName",label:"ชื่อหรือหัวข้อกิจกรรม",placeholder:"ชื่อกิจกรรมหรือหัวข้อ Workshop"},{key:"activityType",label:"รูปแบบกิจกรรม",placeholder:"เช่น Workshop, Talk, Community Meetup"},{key:"participants",label:"จำนวนผู้เข้าร่วมโดยประมาณ",placeholder:"เช่น 20–30 คน"},{key:"spaceNeeds",label:"ลักษณะพื้นที่และอุปกรณ์ที่ต้องใช้",placeholder:"เช่น ที่นั่ง โต๊ะ โปรเจกเตอร์ ระบบเสียง",type:"textarea"}]},
  consultation:{ heading:"ข้อมูลสำหรับประเมินโอกาส",partner:"brand",businessLabel:"ชื่อธุรกิจ / โครงการ",locationLabel:"พื้นที่ดำเนินธุรกิจ",locationPlaceholder:"ระบุจังหวัด ทำเล หรือพื้นที่เป้าหมาย",fields:[{key:"consultationTopic",label:"เรื่องที่ต้องการปรึกษา",placeholder:"ระบุหัวข้อหรือโอกาสที่ต้องการให้ทีมช่วยประเมิน"},{key:"currentSituation",label:"สถานการณ์ปัจจุบัน",placeholder:"อธิบายสิ่งที่มีอยู่และสิ่งที่กำลังดำเนินการ",type:"textarea"},{key:"desiredOutcome",label:"ผลลัพธ์ที่ต้องการ",placeholder:"คุณต้องการให้ธุรกิจหรือโครงการไปถึงจุดใด",type:"textarea"},{key:"challenge",label:"ปัญหาหรือสิ่งที่ยังตัดสินใจไม่ได้",placeholder:"กรุณาให้รายละเอียดเพื่อให้ทีมประเมินได้ตรงประเด็น",type:"textarea"}]},
};

const initial: BookingInput = { requestKey:"",service:"products",partnerType:"space",business:"",location:"",date:"",timeWindow:"",name:"",phone:"",email:"",detail:"",requestData:{},consent:false };
export default function LeadBrief() {
  const [data,setData]=useState(initial); const [step,setStep]=useState(1); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [booking,setBooking]=useState<Booking|null>(null); const submitting=useRef(false); const heading=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{ const p=new URLSearchParams(window.location.search); const requested=p.get("service") || "products"; const service=Object.hasOwn(formConfigs,requested) && requested!=="consultation"?requested:"products"; const config=formConfigs[service]; setData(d=>({...d,service,partnerType:config.partner,requestData:{}})); },[]);
  const config=useMemo(()=>formConfigs[data.service] || formConfigs.consultation,[data.service]);
  function update(key:keyof BookingInput,value:string|boolean){setData(d=>({...d,[key]:value}));setError("");}
  function updateRequest(key:string,value:string){setData(d=>({...d,requestData:{...d.requestData,[key]:value}}));setError("");}
  function review(e:FormEvent<HTMLFormElement>){e.preventDefault();const candidate={...data,requestKey:data.requestKey||crypto.randomUUID(),consent:true};const problem=validateBooking(candidate);if(problem){setError(problem);return;}setData({...candidate,consent:false});setStep(2);requestAnimationFrame(()=>heading.current?.focus());}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(submitting.current)return;const problem=validateBooking(data);if(problem){setError(problem);return;}submitting.current=true;setBusy(true);setError("");try{const response=await fetch("/api/bookings",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const result=await response.json() as {error?:string;booking?:Booking};if(!response.ok)throw new Error(result.error||"ส่งคำขอไม่สำเร็จ กรุณาลองใหม่");if(!result.booking)throw new Error("ยังไม่ได้รับเลขคำขอ กรุณาลองใหม่");setBooking(result.booking);requestAnimationFrame(()=>heading.current?.focus());}catch(e){setError(e instanceof Error?e.message:"เชื่อมต่อไม่สำเร็จ กรุณาลองใหม่");}finally{submitting.current=false;setBusy(false);}}
  if(booking)return <div className="lead-builder booking-success"><span className="booking-check" aria-hidden="true">✓</span><p className="kicker">REQUEST RECEIVED</p><h2 ref={heading} tabIndex={-1}>ส่งข้อมูลเรียบร้อยแล้ว</h2><p className="status-pill pending">รอทีมตรวจสอบ</p><p>ทีม SPACE CONNEX จะตรวจสอบข้อมูลและติดต่อกลับภายใน 3–5 วันทำการ หากข้อมูลมีความเหมาะสม ทีมจะประสานเพื่อนัดหมายและพูดคุยรายละเอียดในขั้นตอนถัดไป</p><dl className="booking-summary"><div><dt>เลขคำขอ</dt><dd className="booking-reference">{booking.id}</dd></div><div><dt>บริการ</dt><dd>{services[booking.service]}</dd></div></dl><a className="button button-primary" href="/">กลับหน้าเว็บไซต์</a></div>;
  return <div className="lead-builder booking-builder"><ol className="booking-progress" aria-label="ขั้นตอนการส่งคำขอ">{["กรอกข้อมูล","ตรวจทาน","เสร็จสิ้น"].map((label,i)=><li key={label} aria-current={step===i+1?"step":undefined} className={step>=i+1?"active":""}><span>{i+1}</span>{label}</li>)}</ol><p className="selected-service">บริการที่เลือก <strong>{services[data.service as keyof typeof services]}</strong></p><h2 ref={heading} tabIndex={-1}>{step===1?config.heading:"ตรวจทานข้อมูลก่อนส่ง"}</h2>
    {step===1&&<form onSubmit={review}><div className="form-grid"><label><span>{config.businessLabel}</span><input required maxLength={160} value={data.business} onChange={e=>update("business",e.target.value)} placeholder="ชื่อธุรกิจของคุณ" autoComplete="organization"/></label><label><span>{config.locationLabel}</span><input required maxLength={300} value={data.location} onChange={e=>update("location",e.target.value)} placeholder={config.locationPlaceholder}/></label>{config.fields.map(field=><label key={field.key} className={field.type==="textarea"?"full-field":undefined}><span>{field.label}</span>{field.type==="textarea"?<textarea required maxLength={500} rows={4} value={data.requestData[field.key]||""} onChange={e=>updateRequest(field.key,e.target.value)} placeholder={field.placeholder}/>:<input required maxLength={500} value={data.requestData[field.key]||""} onChange={e=>updateRequest(field.key,e.target.value)} placeholder={field.placeholder}/>}</label>)}<label><span>ชื่อผู้ติดต่อ</span><input required maxLength={120} value={data.name} onChange={e=>update("name",e.target.value)} autoComplete="name"/></label><label><span>เบอร์โทรศัพท์</span><input type="tel" required maxLength={30} value={data.phone} onChange={e=>update("phone",e.target.value)} autoComplete="tel" placeholder="เช่น 0812345678"/></label><label className="full-field"><span>อีเมล</span><input type="email" required maxLength={254} value={data.email} onChange={e=>update("email",e.target.value)} autoComplete="email"/></label></div><p className="booking-notice">ทีมจะตรวจสอบข้อมูลและติดต่อกลับภายใน 3–5 วันทำการ</p><button className="button button-gold submit-button">ตรวจทานข้อมูล →</button></form>}
    {step===2&&<form onSubmit={submit}><dl className="booking-summary"><div><dt>บริการ</dt><dd>{services[data.service as keyof typeof services]}</dd></div><div><dt>{config.businessLabel}</dt><dd>{data.business}</dd></div><div><dt>{config.locationLabel}</dt><dd>{data.location}</dd></div>{config.fields.map(field=><div key={field.key}><dt>{field.label}</dt><dd>{data.requestData[field.key]}</dd></div>)}<div><dt>ผู้ติดต่อ</dt><dd>{data.name}<br/>{data.phone}<br/>{data.email}</dd></div></dl><label className="booking-consent"><input type="checkbox" required checked={data.consent} onChange={e=>update("consent",e.target.checked)}/><span>รับทราบว่า SPACE CONNEX จะจัดเก็บข้อมูลนี้เพื่อประเมินคำขอและติดต่อกลับ การส่งข้อมูลยังไม่ใช่การยืนยันพื้นที่ การจับคู่ หรือการให้บริการ</span></label><div className="booking-actions"><button type="button" className="button booking-secondary" onClick={()=>setStep(1)}>แก้ไขข้อมูล</button><button disabled={busy} className="button button-gold">{busy?"กำลังส่ง…":"ยืนยันและส่งข้อมูล"}</button></div></form>}{error&&<p className="booking-error" role="alert">{error}</p>}</div>;
}
