import{getServerSession}from "next-auth";
import{NextResponse}from "next/server";
import{authOptions}from "@/lib/auth";
import{query}from "@/lib/db";
import{validateBooking,type BookingInput}from "@/app/booking-options";
const columns="id,service,partner_type,business,location,name,phone,email,request_data::text,status,team_note,created_at,updated_at";
const allowedStatuses=["pending","reviewing","needs_info","approved","completed","cancelled"];
export async function GET(request:Request){const session=await getServerSession(authOptions);if(!session)return NextResponse.json({error:"กรุณาเข้าสู่ระบบ"},{status:401});const all=new URL(request.url).searchParams.get("scope")==="all";if(all&&session.user.role!=="admin")return NextResponse.json({error:"ไม่มีสิทธิ์ดูข้อมูลนี้"},{status:403});const result=all?await query(`SELECT ${columns} FROM bookings ORDER BY created_at DESC LIMIT 200`):await query(`SELECT ${columns} FROM bookings WHERE user_id=$1 ORDER BY created_at DESC LIMIT 200`,[session.user.id]);return NextResponse.json({bookings:result.rows});}
export async function POST(request:Request){const session=await getServerSession(authOptions);if(!session)return NextResponse.json({error:"กรุณาเข้าสู่ระบบก่อนส่งคำขอ"},{status:401});const body=await request.json().catch(()=>null);const error=validateBooking(body);if(error)return NextResponse.json({error},{status:400});const d=body as BookingInput,id=`SC-${crypto.randomUUID().toUpperCase()}`;const result=await query(`INSERT INTO bookings(id,user_id,request_key,service,partner_type,business,location,name,phone,email,request_data) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11::jsonb) ON CONFLICT(user_id,request_key) DO UPDATE SET updated_at=bookings.updated_at RETURNING ${columns}`,[id,session.user.id,d.requestKey,d.service,d.partnerType,d.business.trim(),d.location.trim(),d.name.trim(),d.phone.trim(),d.email.trim(),JSON.stringify(d.requestData)]);return NextResponse.json({booking:result.rows[0]},{status:201});}
export async function PATCH(request:Request){const session=await getServerSession(authOptions);if(!session)return NextResponse.json({error:"กรุณาเข้าสู่ระบบ"},{status:401});const body=await request.json().catch(()=>null)as{id?:string;status?:string;expectedStatus?:string;teamNote?:string}|null;if(!body?.id||!body.status||!body.expectedStatus||!allowedStatuses.includes(body.status)||typeof body.teamNote!=="string"||body.teamNote.length>1000)return NextResponse.json({error:"ข้อมูลสถานะไม่ถูกต้อง"},{status:400});const current=await query<{user_id:string;status:string}>("SELECT user_id,status FROM bookings WHERE id=$1",[body.id]);const row=current.rows[0];if(!row||(session.user.role!=="admin"&&row.user_id!==session.user.id))return NextResponse.json({error:"ไม่พบรายการ"},{status:404});if(session.user.role!=="admin"&&body.status!=="cancelled")return NextResponse.json({error:"ไม่มีสิทธิ์เปลี่ยนสถานะ"},{status:403});const result=await query("UPDATE bookings SET status=$1,team_note=CASE WHEN $4 THEN $2 ELSE team_note END,updated_at=NOW() WHERE id=$3 AND status=$5",[body.status,body.teamNote.trim(),body.id,session.user.role==="admin",body.expectedStatus]);if(!result.rowCount)return NextResponse.json({error:"รายการถูกเปลี่ยนแปลงแล้ว กรุณาโหลดใหม่"},{status:409});return NextResponse.json({ok:true});}
